spring.datasource.url=jdbc:mysql://localhost:3306/student_dbms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server Port
server.port=5000

# Logging
logging.level.org.springframework.jdbc.core=DEBUG

# Gemini AI API Key
gemini.api.key=AIzaSyBpHOED8z3wyZ7wu6VoVqosZOBW7nD4MXY
